project:
  type: website
  output-dir: docs

website:
  title: "Edalytics (DataForFun)"
  navbar:
    tools:
      - icon: twitter 
        href: https://x.com/home
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



